name: Publish Artifact Parent Services
# teste
on:
  pull_request:
    paths:
      - 'app/**'
      - '.github/workflows/bzn-parent-services.yml'   
    branches:
      - 'main'
      - 'develop'
      - 'bugfix/**'
      - 'hotfix/**'
      - 'release/**'
  push:
    paths:
      - 'app/**'
      - '.github/workflows/bzn-parent-services.yml'  
    branches:
      - 'main'    
  workflow_dispatch:

jobs:
  info-environment:
    name: Identifying the Environment
    permissions: write-all
    uses: brazona/bzn-pgc-infra/.github/workflows/identifier.yml@main
    with:
      github_base_ref: ${{github.base_ref}}
      github_event_name: ${{github.event_name }}
      github_ref_name: ${{github.ref_name}}
  build:
    name: Build and Publish Parent Services
    needs: [info-environment]
    runs-on: ubuntu-latest
    permissions: write-all
    environment:
      name: ${{needs.info-environment.outputs.environment_name}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          save-always: true
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Set up JDK 24
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '24'
      - name: Set up Settings.xml 
        uses: s4u/maven-settings-action@v3.1.0
        with:
          servers: |
            [{
                "id": "github-core",
                "username": "${{ secrets.MAVEN_GITHUB_USERNAME }}",
                "password": "${{ secrets.MAVEN_GITHUB_PASSWORD }}"
            }]  
      - name: Publish package
        run: mvn -f ./app/ clean install package --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB_ACTION }}
          